// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUdsHFsKKcgpnJJH81Qks5dessKJIWQo',
    appId: '1:1078285757343:android:2ad4c70c43c8c95da6ebaa',
    messagingSenderId: '1078285757343',
    projectId: 'jlpt-master-5ad0e',
    storageBucket: 'jlpt-master-5ad0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Env_9YZAAQZjIesS9UW527PWoc-2Kq4',
    appId: '1:1078285757343:ios:573f648f679af855a6ebaa',
    messagingSenderId: '1078285757343',
    projectId: 'jlpt-master-5ad0e',
    storageBucket: 'jlpt-master-5ad0e.firebasestorage.app',
    iosBundleId: 'com.kounotakuya.jlptMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Env_9YZAAQZjIesS9UW527PWoc-2Kq4',
    appId: '1:1078285757343:ios:573f648f679af855a6ebaa',
    messagingSenderId: '1078285757343',
    projectId: 'jlpt-master-5ad0e',
    storageBucket: 'jlpt-master-5ad0e.firebasestorage.app',
    iosBundleId: 'com.kounotakuya.jlptMaster',
  );
}
